### ISSUE TITLE
廢站的資料來源與保留廢站的目的

### ISSUE THREAD

**Issue by perplexedfingers** [billy1125/TRA_time_space_diagram#2]
因為已經廢站了，好像不好確認資料是否正常，畢竟台鐵不提供了。還是我可以從哪裡看到或看出來？
另外，做為時刻表，不知道廢站留著有何打算？是拍照會用到嗎？

**Comment by billy1125** [comment]
您好，其實應該是未提供客運服務的車站，不一定就是已經完全廢除的車站，有些則是特定地標，例如號誌站等等，標示這些車站或地標的目的僅是提供參考，有一些鐵道愛好者仍然參考這類資料，例如就像您所說的，拍攝鐵道會參考。希望以上解答可以替您解惑。
